services:
  db:
    image: postgres:16-alpine
    container_name: rideuleam-db
    environment:
      POSTGRES_USER: rideuleam
      POSTGRES_PASSWORD: rideuleam123
      POSTGRES_DB: rideuleam
    ports:
      - "5432:5432"
    volumes:
      - rideuleam_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rideuleam -d rideuleam"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: rideuleam-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PUERTO: ":8080"
      DB_DRIVER: "postgres"
      DB_DSN: "host=db user=rideuleam password=rideuleam123 dbname=rideuleam port=5432 sslmode=disable"
      JWT_SECRETO: "rideuleam-secreto-docker"
    ports:
      - "8080:8080"

volumes:
  rideuleam_pgdata: