// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type HorariosRutum struct {
	ID     int64
	RutaID int64
	Dia    string
	Hora   string
}

type MantenimientosVehiculo struct {
	ID          int64
	VehiculoID  int64
	FechaInicio string
	FechaFin    string
	Motivo      string
}

type RutasProgramada struct {
	ID          int64
	ConductorID int64
	Origen      string
	Destino     string
	Costo       float64
}

type Usuario struct {
	ID       int64
	Nombre   string
	Correo   string
	Password string
}
