// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarHorarioRuta = `-- name: ActualizarHorarioRuta :one
UPDATE horarios_ruta
SET ruta_id = ?, dia = ?, hora = ?
WHERE id = ?
RETURNING id, ruta_id, dia, hora
`

type ActualizarHorarioRutaParams struct {
	RutaID int64
	Dia    string
	Hora   string
	ID     int64
}

func (q *Queries) ActualizarHorarioRuta(ctx context.Context, arg ActualizarHorarioRutaParams) (HorariosRutum, error) {
	row := q.db.QueryRowContext(ctx, actualizarHorarioRuta,
		arg.RutaID,
		arg.Dia,
		arg.Hora,
		arg.ID,
	)
	var i HorariosRutum
	err := row.Scan(
		&i.ID,
		&i.RutaID,
		&i.Dia,
		&i.Hora,
	)
	return i, err
}

const actualizarMantenimientoVehiculo = `-- name: ActualizarMantenimientoVehiculo :one
UPDATE mantenimientos_vehiculo
SET vehiculo_id = ?, fecha_inicio = ?, fecha_fin = ?, motivo = ?
WHERE id = ?
RETURNING id, vehiculo_id, fecha_inicio, fecha_fin, motivo
`

type ActualizarMantenimientoVehiculoParams struct {
	VehiculoID  int64
	FechaInicio string
	FechaFin    string
	Motivo      string
	ID          int64
}

func (q *Queries) ActualizarMantenimientoVehiculo(ctx context.Context, arg ActualizarMantenimientoVehiculoParams) (MantenimientosVehiculo, error) {
	row := q.db.QueryRowContext(ctx, actualizarMantenimientoVehiculo,
		arg.VehiculoID,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Motivo,
		arg.ID,
	)
	var i MantenimientosVehiculo
	err := row.Scan(
		&i.ID,
		&i.VehiculoID,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Motivo,
	)
	return i, err
}

const actualizarRutaProgramada = `-- name: ActualizarRutaProgramada :one
UPDATE rutas_programadas
SET conductor_id = ?, origen = ?, destino = ?, costo = ?
WHERE id = ?
RETURNING id, conductor_id, origen, destino, costo
`

type ActualizarRutaProgramadaParams struct {
	ConductorID int64
	Origen      string
	Destino     string
	Costo       float64
	ID          int64
}

func (q *Queries) ActualizarRutaProgramada(ctx context.Context, arg ActualizarRutaProgramadaParams) (RutasProgramada, error) {
	row := q.db.QueryRowContext(ctx, actualizarRutaProgramada,
		arg.ConductorID,
		arg.Origen,
		arg.Destino,
		arg.Costo,
		arg.ID,
	)
	var i RutasProgramada
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Origen,
		&i.Destino,
		&i.Costo,
	)
	return i, err
}

const borrarHorarioRuta = `-- name: BorrarHorarioRuta :exec
DELETE FROM horarios_ruta
WHERE id = ?
`

func (q *Queries) BorrarHorarioRuta(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, borrarHorarioRuta, id)
	return err
}

const borrarMantenimientoVehiculo = `-- name: BorrarMantenimientoVehiculo :exec
DELETE FROM mantenimientos_vehiculo
WHERE id = ?
`

func (q *Queries) BorrarMantenimientoVehiculo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, borrarMantenimientoVehiculo, id)
	return err
}

const borrarRutaProgramada = `-- name: BorrarRutaProgramada :exec
DELETE FROM rutas_programadas
WHERE id = ?
`

func (q *Queries) BorrarRutaProgramada(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, borrarRutaProgramada, id)
	return err
}

const crearHorarioRuta = `-- name: CrearHorarioRuta :one
INSERT INTO horarios_ruta (ruta_id, dia, hora)
VALUES (?, ?, ?)
RETURNING id, ruta_id, dia, hora
`

type CrearHorarioRutaParams struct {
	RutaID int64
	Dia    string
	Hora   string
}

func (q *Queries) CrearHorarioRuta(ctx context.Context, arg CrearHorarioRutaParams) (HorariosRutum, error) {
	row := q.db.QueryRowContext(ctx, crearHorarioRuta, arg.RutaID, arg.Dia, arg.Hora)
	var i HorariosRutum
	err := row.Scan(
		&i.ID,
		&i.RutaID,
		&i.Dia,
		&i.Hora,
	)
	return i, err
}

const crearMantenimientoVehiculo = `-- name: CrearMantenimientoVehiculo :one
INSERT INTO mantenimientos_vehiculo (vehiculo_id, fecha_inicio, fecha_fin, motivo)
VALUES (?, ?, ?, ?)
RETURNING id, vehiculo_id, fecha_inicio, fecha_fin, motivo
`

type CrearMantenimientoVehiculoParams struct {
	VehiculoID  int64
	FechaInicio string
	FechaFin    string
	Motivo      string
}

func (q *Queries) CrearMantenimientoVehiculo(ctx context.Context, arg CrearMantenimientoVehiculoParams) (MantenimientosVehiculo, error) {
	row := q.db.QueryRowContext(ctx, crearMantenimientoVehiculo,
		arg.VehiculoID,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Motivo,
	)
	var i MantenimientosVehiculo
	err := row.Scan(
		&i.ID,
		&i.VehiculoID,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Motivo,
	)
	return i, err
}

const crearRutaProgramada = `-- name: CrearRutaProgramada :one
INSERT INTO rutas_programadas (conductor_id, origen, destino, costo)
VALUES (?, ?, ?, ?)
RETURNING id, conductor_id, origen, destino, costo
`

type CrearRutaProgramadaParams struct {
	ConductorID int64
	Origen      string
	Destino     string
	Costo       float64
}

func (q *Queries) CrearRutaProgramada(ctx context.Context, arg CrearRutaProgramadaParams) (RutasProgramada, error) {
	row := q.db.QueryRowContext(ctx, crearRutaProgramada,
		arg.ConductorID,
		arg.Origen,
		arg.Destino,
		arg.Costo,
	)
	var i RutasProgramada
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Origen,
		&i.Destino,
		&i.Costo,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one

INSERT INTO usuarios (nombre, correo, password)
VALUES (?, ?, ?)
RETURNING id, nombre, correo, password
`

type CrearUsuarioParams struct {
	Nombre   string
	Correo   string
	Password string
}

// USUARIOS / AUTH
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.Nombre, arg.Correo, arg.Password)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Correo,
		&i.Password,
	)
	return i, err
}

const listarHorariosPorRutaID = `-- name: ListarHorariosPorRutaID :many
SELECT id, ruta_id, dia, hora
FROM horarios_ruta
WHERE ruta_id = ?
`

func (q *Queries) ListarHorariosPorRutaID(ctx context.Context, rutaID int64) ([]HorariosRutum, error) {
	rows, err := q.db.QueryContext(ctx, listarHorariosPorRutaID, rutaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HorariosRutum
	for rows.Next() {
		var i HorariosRutum
		if err := rows.Scan(
			&i.ID,
			&i.RutaID,
			&i.Dia,
			&i.Hora,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarHorariosRuta = `-- name: ListarHorariosRuta :many

SELECT id, ruta_id, dia, hora
FROM horarios_ruta
`

// HORARIOS DE RUTA
func (q *Queries) ListarHorariosRuta(ctx context.Context) ([]HorariosRutum, error) {
	rows, err := q.db.QueryContext(ctx, listarHorariosRuta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HorariosRutum
	for rows.Next() {
		var i HorariosRutum
		if err := rows.Scan(
			&i.ID,
			&i.RutaID,
			&i.Dia,
			&i.Hora,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMantenimientosPorVehiculoID = `-- name: ListarMantenimientosPorVehiculoID :many
SELECT id, vehiculo_id, fecha_inicio, fecha_fin, motivo
FROM mantenimientos_vehiculo
WHERE vehiculo_id = ?
`

func (q *Queries) ListarMantenimientosPorVehiculoID(ctx context.Context, vehiculoID int64) ([]MantenimientosVehiculo, error) {
	rows, err := q.db.QueryContext(ctx, listarMantenimientosPorVehiculoID, vehiculoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MantenimientosVehiculo
	for rows.Next() {
		var i MantenimientosVehiculo
		if err := rows.Scan(
			&i.ID,
			&i.VehiculoID,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Motivo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMantenimientosVehiculo = `-- name: ListarMantenimientosVehiculo :many

SELECT id, vehiculo_id, fecha_inicio, fecha_fin, motivo
FROM mantenimientos_vehiculo
`

// MANTENIMIENTOS VEHICULO
func (q *Queries) ListarMantenimientosVehiculo(ctx context.Context) ([]MantenimientosVehiculo, error) {
	rows, err := q.db.QueryContext(ctx, listarMantenimientosVehiculo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MantenimientosVehiculo
	for rows.Next() {
		var i MantenimientosVehiculo
		if err := rows.Scan(
			&i.ID,
			&i.VehiculoID,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Motivo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRutasProgramadas = `-- name: ListarRutasProgramadas :many

SELECT id, conductor_id, origen, destino, costo
FROM rutas_programadas
`

// RUTAS PROGRAMADAS
func (q *Queries) ListarRutasProgramadas(ctx context.Context) ([]RutasProgramada, error) {
	rows, err := q.db.QueryContext(ctx, listarRutasProgramadas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RutasProgramada
	for rows.Next() {
		var i RutasProgramada
		if err := rows.Scan(
			&i.ID,
			&i.ConductorID,
			&i.Origen,
			&i.Destino,
			&i.Costo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerHorarioRuta = `-- name: ObtenerHorarioRuta :one
SELECT id, ruta_id, dia, hora
FROM horarios_ruta
WHERE id = ?
`

func (q *Queries) ObtenerHorarioRuta(ctx context.Context, id int64) (HorariosRutum, error) {
	row := q.db.QueryRowContext(ctx, obtenerHorarioRuta, id)
	var i HorariosRutum
	err := row.Scan(
		&i.ID,
		&i.RutaID,
		&i.Dia,
		&i.Hora,
	)
	return i, err
}

const obtenerMantenimientoVehiculo = `-- name: ObtenerMantenimientoVehiculo :one
SELECT id, vehiculo_id, fecha_inicio, fecha_fin, motivo
FROM mantenimientos_vehiculo
WHERE id = ?
`

func (q *Queries) ObtenerMantenimientoVehiculo(ctx context.Context, id int64) (MantenimientosVehiculo, error) {
	row := q.db.QueryRowContext(ctx, obtenerMantenimientoVehiculo, id)
	var i MantenimientosVehiculo
	err := row.Scan(
		&i.ID,
		&i.VehiculoID,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Motivo,
	)
	return i, err
}

const obtenerRutaProgramada = `-- name: ObtenerRutaProgramada :one
SELECT id, conductor_id, origen, destino, costo
FROM rutas_programadas
WHERE id = ?
`

func (q *Queries) ObtenerRutaProgramada(ctx context.Context, id int64) (RutasProgramada, error) {
	row := q.db.QueryRowContext(ctx, obtenerRutaProgramada, id)
	var i RutasProgramada
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Origen,
		&i.Destino,
		&i.Costo,
	)
	return i, err
}

const obtenerUsuarioPorCorreo = `-- name: ObtenerUsuarioPorCorreo :one
SELECT id, nombre, correo, password
FROM usuarios
WHERE correo = ?
`

func (q *Queries) ObtenerUsuarioPorCorreo(ctx context.Context, correo string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obtenerUsuarioPorCorreo, correo)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Correo,
		&i.Password,
	)
	return i, err
}

const obtenerUsuarioPorID = `-- name: ObtenerUsuarioPorID :one
SELECT id, nombre, correo, password
FROM usuarios
WHERE id = ?
`

func (q *Queries) ObtenerUsuarioPorID(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obtenerUsuarioPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Correo,
		&i.Password,
	)
	return i, err
}
