// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarParticipanteViaje = `-- name: ActualizarParticipanteViaje :one
;

UPDATE participante_viajes
SET viaje_id=?, usuario_id=?
WHERE id=?
RETURNING id, viaje_id, usuario_i
`

type ActualizarParticipanteViajeParams struct {
	ViajeID   int64
	UsuarioID int64
	ID        int64
}

func (q *Queries) ActualizarParticipanteViaje(ctx context.Context, arg ActualizarParticipanteViajeParams) (ParticipanteViaje, error) {
	row := q.db.QueryRowContext(ctx, actualizarParticipanteViaje, arg.ViajeID, arg.UsuarioID, arg.ID)
	var i ParticipanteViaje
	err := row.Scan(&i.ID, &i.ViajeID, &i.UsuarioID)
	return i, err
}

const actualizarSolicitudViaje = `-- name: ActualizarSolicitudViaje :one
;

UPDATE solicitud_viajes
SET viaje_id=?, pasajero_id=?, estado=?
WHERE id=?
RETURNING id, viaje_id, pasajero_id, estad
`

type ActualizarSolicitudViajeParams struct {
	ViajeID    int64
	PasajeroID int64
	Estado     string
	ID         int64
}

func (q *Queries) ActualizarSolicitudViaje(ctx context.Context, arg ActualizarSolicitudViajeParams) (SolicitudViaje, error) {
	row := q.db.QueryRowContext(ctx, actualizarSolicitudViaje,
		arg.ViajeID,
		arg.PasajeroID,
		arg.Estado,
		arg.ID,
	)
	var i SolicitudViaje
	err := row.Scan(
		&i.ID,
		&i.ViajeID,
		&i.PasajeroID,
		&i.Estado,
	)
	return i, err
}

const actualizarVehiculo = `-- name: ActualizarVehiculo :one
d;

UPDATE vehiculos
SET conductor_id=?, placa=?, marca=?, modelo=?, capacidad=?
WHERE id=?
RETURNING id, conductor_id, placa, marca, modelo, capacid
`

type ActualizarVehiculoParams struct {
	ConductorID int64
	Placa       string
	Marca       string
	Modelo      string
	Capacidad   int64
	ID          int64
}

func (q *Queries) ActualizarVehiculo(ctx context.Context, arg ActualizarVehiculoParams) (Vehiculo, error) {
	row := q.db.QueryRowContext(ctx, actualizarVehiculo,
		arg.ConductorID,
		arg.Placa,
		arg.Marca,
		arg.Modelo,
		arg.Capacidad,
		arg.ID,
	)
	var i Vehiculo
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Placa,
		&i.Marca,
		&i.Modelo,
		&i.Capacidad,
	)
	return i, err
}

const actualizarViajeInmediato = `-- name: ActualizarViajeInmediato :one
;

UPDATE viaje_inmediatos
SET conductor_id=?, origen=?, destino=?, hora_salida=?, cupos=?, estado=?
WHERE id=?
RETURNING id, conductor_id, origen, destino, hora_salida, cupos, estad
`

type ActualizarViajeInmediatoParams struct {
	ConductorID int64
	Origen      string
	Destino     string
	HoraSalida  string
	Cupos       int64
	Estado      string
	ID          int64
}

func (q *Queries) ActualizarViajeInmediato(ctx context.Context, arg ActualizarViajeInmediatoParams) (ViajeInmediato, error) {
	row := q.db.QueryRowContext(ctx, actualizarViajeInmediato,
		arg.ConductorID,
		arg.Origen,
		arg.Destino,
		arg.HoraSalida,
		arg.Cupos,
		arg.Estado,
		arg.ID,
	)
	var i ViajeInmediato
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Origen,
		&i.Destino,
		&i.HoraSalida,
		&i.Cupos,
		&i.Estado,
	)
	return i, err
}

const borrarParticipanteViaje = `-- name: BorrarParticipanteViaje :execrows
;

DELETE FROM participante_viajes WHERE id=
`

func (q *Queries) BorrarParticipanteViaje(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarParticipanteViaje, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarSolicitudViaje = `-- name: BorrarSolicitudViaje :execrows
;

DELETE FROM solicitud_viajes WHERE id=
`

func (q *Queries) BorrarSolicitudViaje(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarSolicitudViaje, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarVehiculo = `-- name: BorrarVehiculo :execrows
d;

DELETE FROM vehiculos WHERE id
`

func (q *Queries) BorrarVehiculo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarVehiculo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarViajeInmediato = `-- name: BorrarViajeInmediato :execrows
;

DELETE FROM viaje_inmediatos WHERE id=
`

func (q *Queries) BorrarViajeInmediato(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarViajeInmediato, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarParticipanteViajePorID = `-- name: BuscarParticipanteViajePorID :one
;

SELECT id, viaje_id, usuario_id FROM participante_viajes
WHERE id=
`

func (q *Queries) BuscarParticipanteViajePorID(ctx context.Context, id int64) (ParticipanteViaje, error) {
	row := q.db.QueryRowContext(ctx, buscarParticipanteViajePorID, id)
	var i ParticipanteViaje
	err := row.Scan(&i.ID, &i.ViajeID, &i.UsuarioID)
	return i, err
}

const buscarSolicitudViajePorID = `-- name: BuscarSolicitudViajePorID :one
;

SELECT id, viaje_id, pasajero_id, estado FROM solicitud_viajes
WHERE id=
`

func (q *Queries) BuscarSolicitudViajePorID(ctx context.Context, id int64) (SolicitudViaje, error) {
	row := q.db.QueryRowContext(ctx, buscarSolicitudViajePorID, id)
	var i SolicitudViaje
	err := row.Scan(
		&i.ID,
		&i.ViajeID,
		&i.PasajeroID,
		&i.Estado,
	)
	return i, err
}

const buscarVehiculoPorID = `-- name: BuscarVehiculoPorID :one
s;

SELECT id, conductor_id, placa, marca, modelo, capacidad FROM vehiculos
WHERE id
`

func (q *Queries) BuscarVehiculoPorID(ctx context.Context, id int64) (Vehiculo, error) {
	row := q.db.QueryRowContext(ctx, buscarVehiculoPorID, id)
	var i Vehiculo
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Placa,
		&i.Marca,
		&i.Modelo,
		&i.Capacidad,
	)
	return i, err
}

const buscarViajeInmediatoPorID = `-- name: BuscarViajeInmediatoPorID :one
;

SELECT id,conductor_id,origen,destino, hora_salida, cupos, estado FROM viaje_inmediatos
WHERE id =
`

func (q *Queries) BuscarViajeInmediatoPorID(ctx context.Context, id int64) (ViajeInmediato, error) {
	row := q.db.QueryRowContext(ctx, buscarViajeInmediatoPorID, id)
	var i ViajeInmediato
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Origen,
		&i.Destino,
		&i.HoraSalida,
		&i.Cupos,
		&i.Estado,
	)
	return i, err
}

const crearParticipanteViaje = `-- name: CrearParticipanteViaje :one
;

INSERT INTO participante_viajes (viaje_id, usuario_id)
VALUES (?, ?)
RETURNING id, viaje_id, usuario_i
`

type CrearParticipanteViajeParams struct {
	ViajeID   int64
	UsuarioID int64
}

func (q *Queries) CrearParticipanteViaje(ctx context.Context, arg CrearParticipanteViajeParams) (ParticipanteViaje, error) {
	row := q.db.QueryRowContext(ctx, crearParticipanteViaje, arg.ViajeID, arg.UsuarioID)
	var i ParticipanteViaje
	err := row.Scan(&i.ID, &i.ViajeID, &i.UsuarioID)
	return i, err
}

const crearSolicitudViaje = `-- name: CrearSolicitudViaje :one
;

INSERT INTO solicitud_viajes (viaje_id, pasajero_id, estado)
VALUES (?, ?, ?)
RETURNING id, viaje_id, pasajero_id, estad
`

type CrearSolicitudViajeParams struct {
	ViajeID    int64
	PasajeroID int64
	Estado     string
}

func (q *Queries) CrearSolicitudViaje(ctx context.Context, arg CrearSolicitudViajeParams) (SolicitudViaje, error) {
	row := q.db.QueryRowContext(ctx, crearSolicitudViaje, arg.ViajeID, arg.PasajeroID, arg.Estado)
	var i SolicitudViaje
	err := row.Scan(
		&i.ID,
		&i.ViajeID,
		&i.PasajeroID,
		&i.Estado,
	)
	return i, err
}

const crearVehiculo = `-- name: CrearVehiculo :one
?;

INSERT INTO vehiculos (conductor_id, placa, marca, modelo, capacidad)
VALUES (?, ?, ?, ?, ?)
RETURNING id, conductor_id, placa, marca, modelo, capacid
`

type CrearVehiculoParams struct {
	ConductorID int64
	Placa       string
	Marca       string
	Modelo      string
	Capacidad   int64
}

func (q *Queries) CrearVehiculo(ctx context.Context, arg CrearVehiculoParams) (Vehiculo, error) {
	row := q.db.QueryRowContext(ctx, crearVehiculo,
		arg.ConductorID,
		arg.Placa,
		arg.Marca,
		arg.Modelo,
		arg.Capacidad,
	)
	var i Vehiculo
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Placa,
		&i.Marca,
		&i.Modelo,
		&i.Capacidad,
	)
	return i, err
}

const crearViajeInmediato = `-- name: CrearViajeInmediato :one
;

INSERT INTO viaje_inmediatos (conductor_id, origen, destino, hora_salida, cupos, estado)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, conductor_id, origen, destino, hora_salida, cupos, estad
`

type CrearViajeInmediatoParams struct {
	ConductorID int64
	Origen      string
	Destino     string
	HoraSalida  string
	Cupos       int64
	Estado      string
}

func (q *Queries) CrearViajeInmediato(ctx context.Context, arg CrearViajeInmediatoParams) (ViajeInmediato, error) {
	row := q.db.QueryRowContext(ctx, crearViajeInmediato,
		arg.ConductorID,
		arg.Origen,
		arg.Destino,
		arg.HoraSalida,
		arg.Cupos,
		arg.Estado,
	)
	var i ViajeInmediato
	err := row.Scan(
		&i.ID,
		&i.ConductorID,
		&i.Origen,
		&i.Destino,
		&i.HoraSalida,
		&i.Cupos,
		&i.Estado,
	)
	return i, err
}

const listarParticipantesViajes = `-- name: ListarParticipantesViajes :many
;


SELECT id, viaje_id, usuario_id FROM participante_viaje
`

// PARTICIPANTES VIAJES
func (q *Queries) ListarParticipantesViajes(ctx context.Context) ([]ParticipanteViaje, error) {
	rows, err := q.db.QueryContext(ctx, listarParticipantesViajes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParticipanteViaje
	for rows.Next() {
		var i ParticipanteViaje
		if err := rows.Scan(&i.ID, &i.ViajeID, &i.UsuarioID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSolicitudesViajes = `-- name: ListarSolicitudesViajes :many
;


SELECT id, viaje_id, pasajero_id, estado FROM solicitud_viaje
`

// SOLICITUDES VIAJES
func (q *Queries) ListarSolicitudesViajes(ctx context.Context) ([]SolicitudViaje, error) {
	rows, err := q.db.QueryContext(ctx, listarSolicitudesViajes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitudViaje
	for rows.Next() {
		var i SolicitudViaje
		if err := rows.Scan(
			&i.ID,
			&i.ViajeID,
			&i.PasajeroID,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVehiculos = `-- name: ListarVehiculos :many
;





SELECT id, conductor_id, placa, marca, modelo, capacidad FROM vehicul
`

// ==========================================
// MÓDULO 4: USUARIOS Y VEHICULOS
// ==========================================
// VEHICULOS
func (q *Queries) ListarVehiculos(ctx context.Context) ([]Vehiculo, error) {
	rows, err := q.db.QueryContext(ctx, listarVehiculos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehiculo
	for rows.Next() {
		var i Vehiculo
		if err := rows.Scan(
			&i.ID,
			&i.ConductorID,
			&i.Placa,
			&i.Marca,
			&i.Modelo,
			&i.Capacidad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarViajesInmediatos = `-- name: ListarViajesInmediatos :many


SELECT id, conductor_id, origen, destino, hora_salida, cupos, estado FROM viaje_inmediato
`

// ==========================================
// MÓDULO 1: VIAJES INMEDIATOS
// ==========================================
// VIAJES INMEDIATOS
func (q *Queries) ListarViajesInmediatos(ctx context.Context) ([]ViajeInmediato, error) {
	rows, err := q.db.QueryContext(ctx, listarViajesInmediatos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ViajeInmediato
	for rows.Next() {
		var i ViajeInmediato
		if err := rows.Scan(
			&i.ID,
			&i.ConductorID,
			&i.Origen,
			&i.Destino,
			&i.HoraSalida,
			&i.Cupos,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
